ALTER TABLE "Job" ADD COLUMN "archive" INTEGER DEFAULT 0 NOT NULL REFERENCES "Archive" ("id");
ALTER TABLE "Archive" ADD COLUMN "created_at" TEXT DEFAULT "" NOT NULL;
ALTER TABLE "ArchivePart" ADD COLUMN "created_at" TEXT DEFAULT "" NOT NULL;
ALTER TABLE "Job" ADD COLUMN "created_at" TEXT DEFAULT "" NOT NULL;
ALTER TABLE "Storage" ADD COLUMN "created_at" TEXT DEFAULT "" NOT NULL;
ALTER TABLE "Archive" ADD COLUMN "size" TEXT DEFAULT "";
